---
- name: Ping Test
  hosts: all
  gather_facts: false
  tasks:

    - name: Ping servers
      ping:
      register: ping_result

    - name: Display ping results
      debug:
        msg: "{{ item.host }} responded with {{ item.ping }}"
      loop: "{{ ping_result.results }}"
      when: ping_result.results is defined
