---
- name: Ping Test
  hosts: all
  gather_facts: false
  tasks:

    - name: Ping servers
      ping:
      register: ping_result

    - name: Force ping failure
      command: /bin/false
      register: force_failure
      changed_when: force_failure.rc != 0
      failed_when: force_failure.rc == 0

    - name: Display successful ping results
      debug:
        msg: "{{ item.host }} responded successfully"
      loop: "{{ ping_result.results | selectattr('ping', 'equalto', 'pong') | list }}"
      when: ping_result.results | selectattr('ping', 'equalto', 'pong') | list | length > 0

    - name: Display failed ping results
      debug:
        msg: "{{ item.host }} did not respond"
      loop: "{{ ping_result.results | rejectattr('ping', 'equalto', 'pong') | list }}"
      when: ping_result.results | rejectattr('ping', 'equalto', 'pong') | list | length > 0
